defaults:
  - train: 10k
  - dataset: default
  - renderer: default
  - pts_sampler: perspective
  - field: hash3d_anchored
  - shader: sh_shader
  - _self_

dataset_name: kashiwa
case_name: 20230622_loop8_2
exp_name: test

is_continue: false

mode: train

renderer:
  # Appearance embedding to handling unstable lighting conditions
  use_app_emb: true

pts_sampler:
  near: 0.01
  scale_by_dis: true

dataset:
  factor: 1
  bounds_factor: [ 0.25, 2.0 ]

train:
  ray_march_init_fineness: 16
