train:
  pts_batch_size: 262144
  end_iter: 20000
  report_freq: 200
  vis_freq: 2500
  save_freq: 20000
  validate_freq: 100000
  disp_loss_weight: 0.
  learning_rate: 1e-2
  learning_rate_alpha: 1e-1
  learning_rate_warm_up_end_iter: 1000
  var_loss_weight: 1e-2
  var_loss_start: 5000
  var_loss_end: 10000

field:
  type: Hash3DAnchored
  log2_table_size: 19
  rand_bias: true
  mlp_out_dim: 16

shader:
  type: SHShader
  d_in: 32
  d_hidden: 64
  d_out: 3
  degree: 4

pts_sampler:
  sample_l: 3.90625e-3   # 1. / 256.

renderer:
  # Appearance embedding to handling unstable lighting conditions
  use_app_emb: true

dataset_path: None

is_continue: false

dataset:
  factor: 1
  bounds_factor: [ 0.25, 4.0 ]
