nerf_based_localizer:
  ros__parameters:
    particle_num: 100
    render_pixel_num: 128
    noise_position_x: 0.05
    noise_position_y: 0.0125
    noise_position_z: 0.05
    noise_rotation_x: 1.0
    noise_rotation_y: 5.0
    noise_rotation_z: 1.0
    base_score: -1.0
    output_covariance: 0.0000225

    offset_position_x: -0.30
    offset_position_y: -0.002392
    offset_position_z: -0.15993
    offset_rotation_w: 1.0
    offset_rotation_x: 0.0
    offset_rotation_y: 0.0
    offset_rotation_z: 0.0
