nerf_based_localizer:
  ros__parameters:
    runtime_config_path: /root/f2-nerf/ros2/runtime_config_awsim.yaml
    is_awsim: true
    particle_num: 100
    render_pixel_num: 128
    noise_position_x: 0.00625
    noise_position_y: 0.0012
    noise_position_z: 0.00625
    noise_rotation_x: 1.0
    noise_rotation_y: 2.5
    noise_rotation_z: 1.0
    base_score: -1.0
    output_covariance: 0.0000225

    offset_position_x: -0.156678
    offset_position_y: 0.039400
    offset_position_z: -0.018178
    offset_rotation_w: 0.999237
    offset_rotation_x: 0.000162
    offset_rotation_y: -0.033626
    offset_rotation_z: -0.019856
