nerf_based_localizer:
  ros__parameters:
    target_frame: base_link
    particle_num: 50
    render_pixel_num: 128
    noise_position_x: 0.10  # [m]
    noise_position_y: 0.10  # [m]
    noise_position_z: 0.05  # [m]
    noise_rotation_x: 0.05  # [deg]
    noise_rotation_y: 0.05  # [deg]
    noise_rotation_z: 0.10  # [deg]
    base_score: -1.0
    output_covariance: 0.000225
    resize_factor: 10
    optimization_mode: 0
