nerf_based_localizer:
  ros__parameters:
    runtime_config_path: /root/f2-nerf/ros2/runtime_config1.yaml
    is_awsim: false
    target_frame: base_link
    particle_num: 50
    render_pixel_num: 128
    noise_position_x: 0.025
    noise_position_y: 0.0125
    noise_position_z: 0.025
    noise_rotation_x: 1.0
    noise_rotation_y: 2.5
    noise_rotation_z: 1.0
    base_score: -1.0
    output_covariance: 0.0000225
