train:
  pts_batch_size: 262144
  end_iter: 20000
  report_freq: 50
  vis_freq: 2500
  stats_freq: 5000
  save_freq: 20000
  validate_freq: 100000
  tv_loss_weight: 0.1
  ray_march_init_fineness: 16
  ray_march_fineness_decay_end_iter: 10000
  disp_loss_weight: 0.0
  learning_rate: 0.01
  learning_rate_alpha: 0.1
  learning_rate_warm_up_end_iter: 1000
  var_loss_weight: 0.01
  var_loss_start: 5000
  var_loss_end: 10000
dataset:
  factor: 1
  factor_to_infer: 16
  ray_sample_mode: all_images
  data_at_gpu: true
  bounds_factor:
  - 0.25
  - 2.0
  data_path: /root/f2-nerf/data/logiee/20230609_base_link
renderer:
  bg_color: rand_noise
  use_app_emb: true
pts_sampler:
  type: PersSampler
  bbox_min:
  - -1.0
  - -1.0
  - -1.0
  bbox_max:
  - 1.0
  - 1.0
  - 1.0
  sub_div_milestones:
  - 2000
  - 4000
  - 6000
  - 8000
  - 10000
  compact_freq: 1000
  max_oct_intersect_per_ray: 1024
  bbox_levels: 10
  max_level: 16
  split_dist_thres: 1.5
  sample_l: 0.00390625
  scale_by_dis: true
  near: 0.01
field:
  type: Hash3DAnchored
  log2_table_size: 19
  rand_bias: true
  mlp_hidden_dim: 64
  mlp_out_dim: 16
  n_hidden_layers: 1
shader:
  type: SHShader
  d_in: 32
  d_out: 3
  d_hidden: 64
  n_hiddens: 2
  degree: 4
dataset_name: logiee
case_name: 20230609_base_link
exp_name: test
is_continue: true
mode: localize
base_dir: /root/f2-nerf
base_exp_dir: /root/f2-nerf/exp/20230609_base_link/test
